<?php

declare( strict_types=1 );

namespace WPSecurity\Modules\FunctionalQa\ContactForm;

use WPSecurity\Domain\RemediationResult;

/**
 * Submits a test entry through Gravity Forms' documented public API,
 * GFAPI::submit_form(). Gravity Forms is not installed in this development
 * environment, so — unlike ContactForm7Provider — this has been verified
 * against Gravity Forms' published API documentation only, not against a
 * live install. It fails safely (try/catch → RemediationResult::failure())
 * if the API shape differs from what's documented here, and only ever runs
 * when isActive() confirms Gravity Forms is the site's actual active form
 * plugin, so a shape mismatch cannot silently corrupt anything — it simply
 * reports a clear failure. Recommend a manual verification pass against a
 * real Gravity Forms install before relying on this in production.
 */
class GravityFormsProvider implements ContactFormProviderInterface {

	private const TEST_PREFIX = '[WP Security Test]';

	public function id(): string {
		return 'gravity_forms';
	}

	public function label(): string {
		return __( 'Gravity Forms', 'wp-security' );
	}

	public function isActive(): bool {
		return class_exists( 'GFAPI' );
	}

	public function testSubmit( array $params ): RemediationResult {
		if ( ! $this->isActive() ) {
			return RemediationResult::skipped( __( 'Gravity Forms is not active.', 'wp-security' ) );
		}

		$formId = isset( $params['form_id'] ) ? absint( $params['form_id'] ) : 0;

		try {
			$form = $formId > 0 ? \GFAPI::get_form( $formId ) : $this->firstActiveForm();

			if ( ! is_array( $form ) || empty( $form['id'] ) ) {
				return RemediationResult::skipped( __( 'No active Gravity Forms forms were found to test.', 'wp-security' ) );
			}

			$inputValues = $this->buildInputValues( $form );

			$result = \GFAPI::submit_form( (int) $form['id'], $inputValues );

			if ( is_wp_error( $result ) ) {
				return RemediationResult::failure(
					sprintf(
						/* translators: %s: Gravity Forms error message */
						__( 'Test submission failed: %s', 'wp-security' ),
						$result->get_error_message()
					)
				);
			}

			if ( empty( $result['is_valid'] ) ) {
				return RemediationResult::failure(
					__( 'Test submission did not pass Gravity Forms validation.', 'wp-security' ),
					null
				);
			}

			return RemediationResult::success(
				__( 'Test submission succeeded through Gravity Forms.', 'wp-security' ),
				null,
				[ 'form_id' => (int) $form['id'] ]
			);
		} catch ( \Throwable $e ) {
			return RemediationResult::failure(
				sprintf(
					/* translators: %s: exception message */
					__( 'Gravity Forms test submission failed unexpectedly: %s', 'wp-security' ),
					$e->getMessage()
				)
			);
		}
	}

	/**
	 * @return array<string, mixed>|null
	 */
	private function firstActiveForm(): ?array {
		$forms = \GFAPI::get_forms( true );
		$first = $forms[0] ?? null;
		return is_array( $first ) ? $first : null;
	}

	/**
	 * @param array<string, mixed> $form
	 * @return array<int|string, mixed>
	 */
	private function buildInputValues( array $form ): array {
		$values = [];
		$fields = is_array( $form['fields'] ?? null ) ? $form['fields'] : [];

		foreach ( $fields as $field ) {
			if ( ! is_object( $field ) || ! isset( $field->id, $field->type ) ) {
				continue;
			}

			$values[ (string) $field->id ] = match ( (string) $field->type ) {
				'email'                        => 'wp-security-test@example.com',
				'phone'                        => '5555555555',
				'number'                       => '1',
				'website'                      => 'https://example.com',
				'textarea'                     => self::TEST_PREFIX . ' This is an automated test submission generated by the WP Security plugin maintenance check.',
				default                        => self::TEST_PREFIX . ' ' . $field->id,
			};
		}

		return $values;
	}
}
